--- 
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - 
        name: "Checkout code from master branch"
        uses: actions/checkout@v2
      - 
        name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: "${{ secrets.ACCESS_KEY }}"
          aws-region: "${{ github.event.inputs.aws_region }}"
          aws-secret-access-key: "${{ secrets.ACCESS_KEY_SECRET }}"
      - 
        name: "Deploy to AWS CloudFormation"
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with: 
          name: test-stack2
          no-fail-on-empty-changeset: "1"
          parameter-overrides: EC2InstanceType=t2.micro
          template: ct-teplate.yaml
name: "Deploy to AWS CloudFormation"
true: 
  pull_request: 
    branches: 
      - dev
  push: 
    branches: 
      - main
  workflow_dispatch: 
    inputs: 
      aws_region: 
        default: us-east-1
        description: "AWS Region to deploy to"
        required: true
